name: tailscale
services:
  tailscale:
    cap_add:
      - NET_ADMIN
      - NET_RAW
    cpu_shares: 90
    command:
      - /bin/sh
      - -c
      - |
        tailscaled --tun=userspace-networking &
        sleep 2
        tailscale web --listen 0.0.0.0:8240
        wait
    container_name: tailscale
    deploy:
      resources:
        limits:
          memory: 7937M
    hostname: casaos-tailscale
    image: tailscale/tailscale:v1.78.3
    labels:
      icon: https://play-lh.googleusercontent.com/wczDL05-AOb39FcL58L32h6j_TrzzGTXDLlOrOmJ-aNsnoGsT1Gkk2vU4qyTb7tGxRw
    restart: unless-stopped
    stop_grace_period: 1m0s
    volumes:
      - type: bind
        source: /DATA/AppData/RonsTailscale
        target: /var/lib
      - type: bind
        source: /dev/net/tun
        target: /dev/net/tun
    ports: []
    devices: []
    environment: []
    network_mode: host
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: 
  icon: https://play-lh.googleusercontent.com/wczDL05-AOb39FcL58L32h6j_TrzzGTXDLlOrOmJ-aNsnoGsT1Gkk2vU4qyTb7tGxRw
  index: /
  is_uncontrolled: false
  port_map: "8240"
  scheme: http
  store_app_id: tailscale
  title:
    custom: Tailscale
    en_us: tailscale
